from void_liquidity.pipeline.signals.whales import (
    POLYMARKET_WHALE_SIGNALS_COMPLETED,
    POLYMARKET_WHALE_SIGNALS_FAILED,
    POLYMARKET_WHALE_SIGNALS_REQUESTED,
    POLYMARKET_WHALE_SIGNALS_STARTED,
)

__all__ = [
    "POLYMARKET_WHALE_SIGNALS_COMPLETED",
    "POLYMARKET_WHALE_SIGNALS_FAILED",
    "POLYMARKET_WHALE_SIGNALS_REQUESTED",
    "POLYMARKET_WHALE_SIGNALS_STARTED",
]
