POLYMARKET_WHALE_DISCOVERY_REQUESTED = "pipeline.markets.whales.discovery.requested"
POLYMARKET_WHALE_DISCOVERY_STARTED = "polymarket.markets.whales.discovery.started"
POLYMARKET_WHALE_DISCOVERY_COMPLETED = "polymarket.markets.whales.discovery.completed"
POLYMARKET_WHALE_DISCOVERY_FAILED = "polymarket.markets.whales.discovery.failed"
POLYMARKET_WHALE_DISCOVERY_DISCOVERED = (
    "polymarket.markets.whales.discovery.discovered"
)
POLYMARKET_WHALE_DISCOVERY_PERSIST_STARTED = (
    "polymarket.markets.whales.discovery.persist_started"
)
POLYMARKET_WHALE_DISCOVERY_PERSIST_COMPLETED = (
    "polymarket.markets.whales.discovery.persist_completed"
)
POLYMARKET_WHALE_DISCOVERY_PERSIST_FAILED = (
    "polymarket.markets.whales.discovery.persist_failed"
)

POLYMARKET_WHALES_V2_REQUESTED = POLYMARKET_WHALE_DISCOVERY_REQUESTED
POLYMARKET_WHALES_V2_STARTED = POLYMARKET_WHALE_DISCOVERY_STARTED
POLYMARKET_WHALES_V2_COMPLETED = POLYMARKET_WHALE_DISCOVERY_COMPLETED
POLYMARKET_WHALES_V2_FAILED = POLYMARKET_WHALE_DISCOVERY_FAILED
POLYMARKET_WHALES_V2_DISCOVERED = POLYMARKET_WHALE_DISCOVERY_DISCOVERED
POLYMARKET_WHALES_V2_PERSIST_STARTED = POLYMARKET_WHALE_DISCOVERY_PERSIST_STARTED
POLYMARKET_WHALES_V2_PERSIST_COMPLETED = POLYMARKET_WHALE_DISCOVERY_PERSIST_COMPLETED
POLYMARKET_WHALES_V2_PERSIST_FAILED = POLYMARKET_WHALE_DISCOVERY_PERSIST_FAILED
