"""init

Revision ID: d2356fc50388
Revises: 
Create Date: 2026-05-25 19:45:45.006904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2356fc50388'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_whales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proxy_wallet', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proxy_wallet')
    )
    op.create_index('ix_tracked_whales_proxy_wallet', 'tracked_whales', ['proxy_wallet'], unique=False)
    op.create_table('whale_tracker_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('profile_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('candidate_wallet_count', sa.Integer(), nullable=False),
    sa.Column('checked_wallet_count', sa.Integer(), nullable=False),
    sa.Column('accepted_wallet_count', sa.Integer(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whale_tracker_runs')
    op.drop_index('ix_tracked_whales_proxy_wallet', table_name='tracked_whales')
    op.drop_table('tracked_whales')
    # ### end Alembic commands ###
